"""add-redacted-to-log

Revision ID: 121a884e23d5
Revises: b43a769e91fc
Create Date: 2022-06-28 09:18:35.304795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121a884e23d5'
down_revision = 'b43a769e91fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('redacted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'redacted')
    # ### end Alembic commands ###
