"""Initial migration

Revision ID: b43a769e91fc
Revises: 
Create Date: 2022-06-27 11:26:54.376422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43a769e91fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('star_date', sa.DateTime(), nullable=False),
    sa.Column('log_entry', sa.Text(), nullable=False),
    sa.Column('crew_member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crew_member_id'], ['crew_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('crew_member')
    # ### end Alembic commands ###
